line_ending = "Lf"

[transformations]
enable_uses_section = false
enable_unit_program_section = false
enable_single_keyword_sections = false
enable_procedure_section = false
enable_text_transformations = true

[text_changes]
space_inside_brace_comments = true
