indentation = "  "
line_ending = "Lf"
space_after_comma = true

[uses_section]
uses_section_style = "CommaAtTheEnd"
override_sorting_order = []
module_names_to_update = ["System:Classes", "System:Generics.Collections", "System:SysUtils"]

[transformations]
enable_uses_section = true
enable_unit_program_section = true
enable_single_keyword_sections = true
enable_procedure_section = true
enable_text_transformations = false
